### ISSUE TITLE
Doesn't work in Version 2023.1 of Webstorm

### ISSUE THREAD

**Issue by cg-ite** [ServiceStack/ServiceStackIDEA#3]
Hello,

your useful addin doesn't work in Webstorm 2023.1 anymore. I'm getting the following error message: 

> Plugin 'ServiceStack' requires plugin 'com.intellij.java' to be installed

I have to disable it. I can't install the zip of version 1.3 either.
I hope you can fix it 🙂

Greetings,
Christian

**Comment by Layoric** [comment]
Hi @cg-ite , thanks for reporting. We've updated the plugin to support the latest version of WebStorm 2023.1, it will be available from the Jetbrains Plugin Marketplace in a few days as it goes through their QA process.

If you want to try it out early, you can use the `Releases` page on this repository, [v1.3.1](https://github.com/ServiceStack/ServiceStackIDEA/releases/download/v1.3.1/ServiceStack-1.3.1.zip). Let us know if you have any other issues. Thanks!
